[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Joseph Roque <contact@josephroque.ca>"]
edition = "2018"

[dependencies]
aoc_util = { path = "../../../util/rust/util" }
aoc_computer = { path = "../../../util/rust/2019_computer" }
