#!/usr/bin/env python3

from argparse import ArgumentParser
import sys

from aoc_util.commands.command import Command
from aoc_util.commands.create import Create
from aoc_util.commands.fetch import Fetch
from aoc_util.commands.open import Open
from aoc_util.commands.run import Run
from aoc_util.commands.set import Set
from aoc_util.commands.submit import Submit
from aoc_util.commands.test import Test
from aoc_util.session import Session


def parse_args(args=None):
    if args is None:
        args = sys.argv[1:]

    parser = ArgumentParser(description="Advent of Code")

    subparsers = parser.add_subparsers(title="commands", dest="command")
    for command in list(Command):
        subparser = subparsers.add_parser(command.value)
        runner_for_command(command).build_parser(subparser)

    parsed = parser.parse_args(args)
    command = Command(parsed.command)
    session = Session(command, parsed)

    runner_for_command(command)().run(session)


def runner_for_command(command: Command):
    if command == Command.CREATE:
        return Create
    elif command == Command.FETCH:
        return Fetch
    elif command == Command.OPEN:
        return Open
    elif command == Command.RUN:
        return Run
    elif command == Command.SUBMIT:
        return Submit
    elif command == Command.SET:
        return Set
    elif command == Command.TEST:
        return Test


if __name__ == "__main__":
    parse_args()
