[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Joseph Roque <contact@josephroque.ca>"]
edition = "2018"

[dependencies]
itertools = "0.8.2"
aoc_util = { path = "../../../helpers/rust/util" }
opcode_computer = { path = "../../../helpers/rust/opcode_computer" }
